### PR TITLE
[CrossEPG] Try fix last commit [bf16588] - add pt translation

### PR DESCRIPTION
**Pull request by nunigaia**

### CODE REVIEW

**Comment by AbuBaniaz** [comment]
Shall I delete the po file?

**Comment by nunigaia** [comment]
If not needed, you can!

**Comment by Ev0-BH** [comment]
Shall I just revert this commit ?

**Comment by nickersk** [comment]
nn, its ok now, both .mo and .po are ok now, thx @atvcaptain

**Comment by nickersk** [comment]
updated first comment ...

**Comment by Ev0-BH** [comment]
https://github.com/oe-alliance/e2openplugin-CrossEPG/commit/14d2184d93bf23251387d40e7aa8ad7f591fb724#commitcomment-39157403

**Comment by nunigaia** [comment]
> nn, its ok now, both .mo and .po are ok now, thx @atvcaptain

Thanks for the fix @atvcaptain and sorry for my mistake.

**Pull request merged**
