### PR TITLE
add openplus image in menu EPG

### PR DESCRIPTION
**Pull request by villak**

### CODE REVIEW

**Comment by atvcaptain** [comment]
? not a oe-a team member

**Comment by AbuBaniaz** [comment]
Hi, if this is a problem, please revert.

**Comment by villak** [comment]
i am not member.

**Comment by Schimmelreiter** [comment]
There are non-oe-a members building from oe-a ...

**Comment by RobvanderDoes** [comment]
LOL, I was just about to ask who they are.....

**Comment by AbuBaniaz** [comment]
I suppose people would build from e2-open version  if someone maintained it.

**Comment by Schimmelreiter** [comment]
I see no problem with that :)
Better they use oe-a than PLi ***vbeg***

**Comment by RobvanderDoes** [comment]
Indeed no problem when using our resources, but do we need to adjust them to their needs?

**Comment by AbuBaniaz** [comment]
How many OE-A members do not have an EPG menu or don't want  CrossEPG in it? If the numbers who do not have it is fewer, surely it would be better to place the plugin in the EPG menu for everyone apart from those who do not want it?

**Comment by Schimmelreiter** [comment]
> Indeed no problem when using our resources, but do we need to adjust them to their needs?
Asking the other way around:
Would you even mind asking that if it was a bug-fix or enhancement?

My vote:
Let them. "What goes around, comes around." or as we say in German "Wie man in den Wald hineinruft ..."

**Comment by Schimmelreiter** [comment]
> How many OE-A members do not have an EPG menu or don't want CrossEPG in it? If the numbers who do not have it is fewer, surely it would be better to place the plugin in the EPG menu for everyone apart from those who do not want it?

Doesn't seem to be too many. From what I have in my mind, only openmips is missing.

**Comment by atvcaptain** [comment]
idee was we help us , and not copy all and keeps own things private

**Comment by AbuBaniaz** [comment]
I am reverting this as some people are unhappy. It is not an OE_A resource, it is a GitHub resource

**Comment by ViX-Sicilian** [comment]
@ captain, unfortunately there's many leachers out taking our work and using closed source gits for their e2.

**Comment by Schimmelreiter** [comment]
Well, not up to me to decide.

I'm just telling my opinion and that is not to be too strict:
We would have accepted a fix/enhancement and we are more likely to see those if we also accept this.

@ViX-Sicilian: Their git is public - https://github.com/Linux-Box

**Comment by ViX-Sicilian** [comment]
My comment wasn't aimed at them, it was in general.

**Comment by AbuBaniaz** [comment]
Is it possible to make the plugin appear in EPG menu for everyone if EPG menu exists?

**Comment by atvcaptain** [comment]
you dont unterstand my message, i have np with all, i make all public so all user can use it, we all here in oe-a speed many time to fix the issues, then other teams use it and keep fixes privat , this is not working over long time, and one think then you fork commits
 dont rename the real commit name this is not fair from the first commit user

**Comment by iqas** [comment]
We understand that it is problematic commit.. Our code is public and will remain so in the future. We will include a patch on the compilation if the use of CrossEPG in Openplus image is not a problem for oe-a team
The problem is that our developers are few and we go slowly. We continue to cooperate with your project especially in Spanish translations as until now.
Greetings to the whole team

**Comment by AbuBaniaz** [comment]
Rob and yourself are the only people to have objected. I have got a telling off on our forum.

Being insular does not help further open source software. He can quite happily fork the repo and make his changes and say "stuff you, I have what I want". Any improvements he makes, will then stay on his repo.  E2openplugins rejected Andy's changes, we forked and plugin split. Now PLi don't even build from it saying it is broken.

**Comment by AbuBaniaz** [comment]
Their images are here
http://feeds.open-plus.es/openplus/1.0/images/

**Comment by RobvanderDoes** [comment]
> Rob and yourself are the only people to have objected. I have got a telling off on our forum.

No objections from my side (yet); I was wondering what would be correct.

**Pull request merged**
