### PR TITLE
update dbconverter to ENIGMA_EPG_V8

### PR DESCRIPTION
**Pull request by LraiZer**
New ENIGMA_EPG_V8 file structure
SEE: https://github.com/OpenPLi/enigma2/commit/d41da655e446fdc93b6be22b0dcaa72bcb15230a

### CODE REVIEW

**Comment by arion75** [comment]
Hello
Where can I get this py3 dev crossepg you fixed for the test?

**Comment by LraiZer** [comment]
Regarding your crash log, I was originally having a different earlier crash than yours with OpenATV and the eEPGCache::crossepgImportEPGv21 patch.

OpenATV was crashing [HERE](https://github.com/openatv/enigma2/blob/76ddda3d745fdab92b25f7ce5de60fdadb2e97d0/lib/dvb/epgcache.cpp#L488) with a historySecond subtraction crash. Removing the historySecond subtraction to how it is in OpenViX code [HERE](https://github.com/OpenViX/enigma2/blob/ea04c8fd3743ee345c5e0dd026a080485512c91b/lib/dvb/epgcache.cpp#L580) moved my crash to a later point and i guess the same crash as yours now.

`time_t now = ::time(0) - historySeconds;`
`time_t now = ::time(0);`

I think OpenATV and OpenViX may now be crashing at the same code point [HERE](https://github.com/openatv/enigma2/blob/76ddda3d745fdab92b25f7ce5de60fdadb2e97d0/lib/dvb/epgcache.cpp#L496)

`EventCacheItem &servicemap = eventDB[service];`

**Comment by arion75** [comment]
Hello.
ATV 7.0. 
EPG for satellite channels. OK. Thanks.
EPG for IPTV channels. No.  Does not convert.
If possible, please correct it. On the old ENIGMA_EPG_V7 it worked.

**Comment by TwolDE2** [comment]
@arion75 Where is the IPTV from and how is the EPG assigned? I am assuming that either you assign a service ID or use an EPG from a provider?
Changes V7 —-> V8 are unlikely to cause an issue, and apart from the code to create the epg.dat, only basic python2 —-> python3 conversion has taken place. The C++ code and the binaries used have not changed

**Comment by TwolDE2** [comment]
LraiZer - that V21 C++ code is beyond me, so I am assuming that we go with the other EPGcache patch (hence the recent changes) - - it works for me across all the boxes using OpenViX py3 images. EV0 has asked me to clear up a few things which I will look at tomorrow.(menu/Setup options)

**Comment by arion75** [comment]
@TwolDE2
the service ID is assigned using the e2m3u2bouquet plugin (Mod from Dorik1972).
source TV guide
http://epg.openboxfan.com/xmltv-t-sd.xml.gz

**Comment by TwolDE2** [comment]
@arion75 why don‘t you use the epg-importer option in e2m3u2bouquet which will import from the provider a file ?

**Comment by arion75** [comment]
@ TwolDE2
Thanks. I use it.

**Comment by TwolDE2** [comment]
@LraiZer - this url in the rytec loader no longer valid (url = "http://rytecepg.dyndns.tv/epg_data/crossepgsources.gz") any idea what it should be? (I am currently using the OpenViX rytec url)

**Comment by LraiZer** [comment]
> LraiZer - that V21 C++ code is beyond me, so I am assuming that we go with the other EPGcache patch (hence the recent changes) - - it works for me across all the boxes using OpenViX py3 images. EV0 has asked me to clear up a few things which I will look at tomorrow.(menu/Setup options)
 
@TwolDE2 
Now that load() patch is working again for all, try reverting the code back to patch V21 as being first detected patch and then add an eEPGCache.getInstance() in loadEPG2() for the V21 function instead of the current 'None'? 

	def loadEPG2(self):
		print("[CrossEPG_Loader] loading data with crossepg patch v2")
		if six.PY3:
			_enigma.eEPGCache_crossepgImportEPGv21(eEPGCache.getInstance(), self.db_root)
		else:
			self.xepgpatch(eEPGCache.getInstance(), self.db_root)			
		self.closeAndCallback(True)


[CrossEPG_Loader] loading data with crossepg patch v2
[eEPGCache] start crossepg import
[eEPGCache] 0 aliases groups in crossepg db
[eEPGCache] imported 140620 events from crossepg db
[eEPGCache] 9222392 bytes for cache used

**Comment by LraiZer** [comment]
> @LraiZer - this url in the rytec loader no longer valid (url = "http://rytecepg.dyndns.tv/epg_data/crossepgsources.gz") any idea what it should be? (I am currently using the OpenViX rytec url)

Ask Doglover on OpenPLi forum in EPG support, i think he may have stopped supporting crossepg sources in favour of XMLTV-Import plugin support only?

**Comment by AbuBaniaz** [comment]
Vix has  a separate URL so that we can trim and remove hosts. This was done because at the time, WanWizard was blocking non-PLI and non-Enigma2 devices owing to Kodi devices hammering his server.

**Comment by AbuBaniaz** [comment]
I don't think the urls were updated when the last change occurred.

**Comment by TwolDE2** [comment]
@LraiZer -OK will try that but I am told the copy and load is much faste(and I am not a regular user, so no idea) - although of course all the conversion has already been done.

**Comment by TwolDE2** [comment]
@LraiZer -  OK runs fine, will reinstate both “patches“ in code
Thank you for all your help and knowledge in getting this to work.
This branch (dev) should also work in python2, as I believe there are checks throughout for py2/py3 changes

**Comment by TwolDE2** [comment]
One comment is that it obviously should be run overnight/non active times, as using theV21 patch there is a lockout for about 2 minutes after the load says it has finished.(I guess its still processing)

**Comment by LraiZer** [comment]
Maybe something to try in crossepg_loader.py..?

line:93

		if six.PY3:
			try:
				self.xepgpatch = instancemethod(_enigma.eEPGCache_crossepgImportEPGv21, eEPGCache.getInstance())
				print("[CrossEPG_Loader] patch crossepg v2.1 found")
			except Exception as e:
				print("[CrossEPG_Loader] patch crossepg v2.1 not found e = %s" % e)
				self.xepgpatch = None

line:200

	def loadEPG2(self):
		if six.PY3:
			self.xepgpatch(self.db_root)
		else:
			self.xepgpatch(eEPGCache.getInstance(), self.db_root)
		self.closeAndCallback(True)

**Comment by arion75** [comment]
@ TwolDE2
perfectly ships for IPTV guide via CrossEPG OpenViX  6.0.  Hooray, hooray. Hooray

OpenATV 7.0
 it can't do that. It can be seen that they have a mistake in their image.

**Comment by arion75** [comment]
Thank you very much. After upgrading to version 0.9.0, everything worked as before. Thanks, everything is great.

**Pull request merged**
